# main.s — S4D Galaxy Classifier Demo Program
# Milestone 3 — RISC-V 32-bit Assembly
#
# This is the demo program required by Task 1.
# It loads a real test image (from image.s, generated by gen_image.py)
# and executes the complete 9-stage forward pass:
#
#   1. Hilbert Scan        : (4096,) → (4096,)
#   2. Input Projection    : (4096,) → (4096,64)
#   3. S4D Layer 1         : (4096,64) → (4096,64)
#   4. GELU                : in-place on (4096,64)
#   5. S4D Layer 2         : (4096,64) → (4096,64)
#   6. GELU                : in-place on (4096,64)
#   7. TakeLastTimestep    : (4096,64) → (64,)
#   8. FC Layer            : (64,) → (4,)
#   9. Softmax             : (4,) → (4,)
#
# How to build and run:
#   python3 gen_image.py 0          # generate image.s from test image 0
#   ./build.sh -a main.s -l nn.s -l math.s -l weights.s -l image.s
#
# How to read the result:
#   The predicted class (0-3) is in register a0 at the unimp halt.
#   The VeeR-ISS log will show the last integer register write to a0.
#   Additionally, probs[] in .data holds the 4 softmax probabilities.
#
# Class mapping:
#   0 = smooth_round
#   1 = smooth_cigar
#   2 = edge_on_disk
#   3 = unbarred_spiral
#
# test_image and true_label are defined in image.s (linked separately).
# They are declared extern here — no definition in this file.

.section .text
.globl _start
_start:
    # ── Step 1: Run full forward pass ───────────────────────────────
    # model_forward(a0 = image*)  →  returns predicted class in a0
    la      a0, test_image
    call    model_forward
    # a0 = argmax(softmax(logits)) = predicted class index (0-3)

    # ── Step 2: Halt — result is in a0 ──────────────────────────────
    # The simulator stops here. Inspect the log:
    #   grep -E "^\s*a0" build/logs/main.txt | tail -1
    # Or check the last integer register write to a0 before unimp.
    #
    # The 4 softmax probabilities are in the global buffer probs[0..3]:
    #   la t0, probs
    #   flw fa0, 0(t0)   # class 0 probability
    #   flw fa1, 4(t0)   # class 1 probability
    #   flw fa2, 8(t0)   # class 2 probability
    #   flw fa3, 12(t0)  # class 3 probability
    #
    # Load probs into fa0-fa3 so they appear in the log
    la      t0, probs
    flw     fa0, 0(t0)      # prob[0] = P(smooth_round)
    flw     fa1, 4(t0)      # prob[1] = P(smooth_cigar)
    flw     fa2, 8(t0)      # prob[2] = P(edge_on_disk)
    flw     fa3, 12(t0)     # prob[3] = P(unbarred_spiral)

    # a0 still holds predicted class from model_forward
    unimp
